<a href="https://colab.research.google.com/github/MuhammadSafeer786/ArticleBot/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Recources :

1- Github https://github.com/mrdbourke/pytorch-deep-learning

2- Book https://learnpytorch.io

3- Pytorch https://pytorch.org

4- Pytorch Forum

In [53]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating Tensors

In [54]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [55]:
scalar.ndim

0

In [56]:
scalar.item()

7

In [57]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [58]:
vector.ndim

1

In [59]:
vector.shape

torch.Size([2])

In [60]:
vector[0]

tensor(7)

In [61]:
Matrix = torch.tensor([[7,8],[9,7]])
Matrix

tensor([[7, 8],
        [9, 7]])

In [62]:
Matrix[1]

tensor([9, 7])

In [63]:
Tensor = torch.tensor([[[2,4,5],[4,9,6],[8,5,2]]])

**.size .shape .ndim** but **.item** is only apllicable on scalar

In [64]:
Tensor.ndim

3

In [65]:
Tensor.shape

torch.Size([1, 3, 3])

### Random Tensor
Why random tensors?

`Networks typicaly start with random numbers`

In [66]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1805, 0.4825, 0.2686, 0.1408],
        [0.7579, 0.1169, 0.9728, 0.5047],
        [0.4919, 0.5435, 0.1920, 0.4932]])

In [67]:
random_tensor.ndim

2

In [68]:
rand_img_tensor = torch.rand(size=(3,224,224))

In [69]:
rand_img_tensor

tensor([[[0.4749, 0.0941, 0.1364,  ..., 0.1132, 0.6131, 0.0854],
         [0.5352, 0.2889, 0.5913,  ..., 0.2435, 0.7539, 0.5811],
         [0.4221, 0.4834, 0.2398,  ..., 0.9443, 0.1743, 0.5264],
         ...,
         [0.6272, 0.4500, 0.5890,  ..., 0.7239, 0.3162, 0.0596],
         [0.6831, 0.9689, 0.8595,  ..., 0.3069, 0.7110, 0.4506],
         [0.6225, 0.4547, 0.4092,  ..., 0.7875, 0.8275, 0.7384]],

        [[0.6331, 0.6580, 0.6227,  ..., 0.0233, 0.0977, 0.5208],
         [0.7864, 0.9949, 0.3963,  ..., 0.3339, 0.8099, 0.7897],
         [0.4159, 0.1925, 0.5524,  ..., 0.4195, 0.7804, 0.6490],
         ...,
         [0.5427, 0.3199, 0.1181,  ..., 0.3806, 0.7593, 0.8133],
         [0.1372, 0.6393, 0.2907,  ..., 0.0861, 0.7443, 0.3183],
         [0.7273, 0.8777, 0.6444,  ..., 0.6339, 0.1393, 0.9686]],

        [[0.2392, 0.8477, 0.9947,  ..., 0.9432, 0.3000, 0.8386],
         [0.0826, 0.3887, 0.6113,  ..., 0.7840, 0.8827, 0.7843],
         [0.4974, 0.1887, 0.0380,  ..., 0.6854, 0.7493, 0.

In [70]:
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [73]:
matrix.dtype

torch.int64

In [74]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [76]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
torch.zeros_like(random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Data Types in Tensors

In [89]:
temp_tensor = torch.tensor([3.0,6.0,9.0],
                           dtype= torch.bfloat16,
                           device= 'cpu',
                           requires_grad= False) #track gradients

In [87]:
temp_tensor.dtype

torch.bfloat16

In [92]:
tensor32 = temp_tensor.type(torch.float32) # explicit type casting

In [95]:
result = temp_tensor*tensor32
result

tensor([ 9., 36., 81.])

In [96]:
result.dtype

torch.float32